version: '3.8'

networks: 
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - postgres
        networks: 
            - laravel

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DATABASE: laravel
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_ROOT_PASSWORD: rootpass
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
    
    npm:
        image: node:lts
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - postgres
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel